
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
  namespace: lab
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-shell-statefulset
  namespace: lab
  labels:
    kbash: "true"
spec:
  serviceName: "user-shell-service"
  replicas: 1
  selector:
    matchLabels:
      app: user-shell
  template:
    metadata:
      labels:
        app: user-shell
        kbash: "true"
    spec:
      containers:
        - name: user-shell-container
          image: containers.stagingterritory.com/lab/bifrost:latest
          imagePullPolicy: Always
          command: ["python", "-u", "/opt/startup.py"]
          volumeMounts:
            - mountPath: /home/user/<username>
              name: user-storage
          stdin: true
          tty: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: user-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

